# Formation of UPX Metadata

In [1]:
# importing all libraries
import os
import re
from pathlib import Path
import numpy as np
import pandas as pd
import soundfile as sf
from IPython.display import Audio, display

In [2]:
# reading the speaker information file and making a dataframe
upx_info_df=pd.read_csv("UPX_info.csv")
upx_info_df.head()

  SPEAKER-ID  GENDER  AGE-Y  AGE-M    AGE                         SSD SUBTYPE
0        01F  Female      8      8   8.67  inconsistent phonological disorder
1        02F  Female      7      8   7.67               phonological disorder
2        03F  Female     10     11  10.92         childhood apraxia of speech
3        04M    Male      7      2   7.17                  phonological delay
4        05M    Male      6      5   6.42                      vowel disorder

In [3]:
# checking the shape of dataset
upx_info_df.shape

(20, 6)

In [4]:
# checking for any missing values
upx_info_df.isna().sum()

SPEAKER-ID     0
GENDER         0
AGE-Y          0
AGE-M          0
AGE            0
SSD SUBTYPE    0
dtype: int64

In [5]:
# now forming a metatable of the data based inside core-upx directory

dataset = "upx" # storing dataset name as a string
dataset_root = Path("core-upx") # storing the folder path name

# sub-folders inside the root folder
core_dir = dataset_root/ "core"
lab_dir = dataset_root/ "speaker_labels"/ "lab"

rows = []

# now looping through dataset

# looping through each speaker folder
for speaker_dir in sorted(core_dir.iterdir()): # iterate is used to make a iterative generator for the for loop because core_dir is just a path
    if not speaker_dir.is_dir(): # check for folder only
        continue # skip if not found

    speaker_id = speaker_dir.name # taking the folder name

    for session_dir in sorted(speaker_dir.iterdir()):
        if not session_dir.is_dir(): # check for folder only
            continue

        session_id = session_dir.name

        for wav_path in sorted(session_dir.glob("*.wav")):
            file_id = wav_path.stem # skip the extension part

            txt_path = session_dir/ f"{file_id}.txt"
            full_id = f"{speaker_id}-{session_id}-{file_id}" # pattern to match the text file format
            lab_path = lab_dir/ f"{full_id}.lab"

            rows.append({
                "dataset_name": dataset,
                "speaker_id": speaker_id,
                "session_id": session_id,
                "file_id" : file_id, 
                "full_id": full_id,
                "raw_wav_path": str(wav_path),
                "txt_path": str(txt_path) if txt_path.exists() else None,
                "speaker_label_path": str(lab_path) if lab_path.exists() else None,
                "class_label": 1
            })

upx_metadata=pd.DataFrame(rows)
upx_metadata.head()

,dataset_name,speaker_id,session_id,file_id,full_id,raw_wav_path,txt_path,speaker_label_path,class_label
0,upx,01F,BL1,001E,01F-BL1-001E,core-upx/core/01F/BL1/001E.wav,core-upx/core/01F/BL1/001E.txt,core-upx/speaker_labels/lab/01F-BL1-001E.lab,1
1,upx,01F,BL1,002E,01F-BL1-002E,core-upx/core/01F/BL1/002E.wav,core-upx/core/01F/BL1/002E.txt,core-upx/speaker_labels/lab/01F-BL1-002E.lab,1
2,upx,01F,BL1,003A,01F-BL1-003A,core-upx/core/01F/BL1/003A.wav,core-upx/core/01F/BL1/003A.txt,core-upx/speaker_labels/lab/01F-BL1-003A.lab,1
3,upx,01F,BL1,004A,01F-BL1-004A,core-upx/core/01F/BL1/004A.wav,core-upx/core/01F/BL1/004A.txt,core-upx/speaker_labels/lab/01F-BL1-004A.lab,1
4,upx,01F,BL1,005A,01F-BL1-005A,core-upx/core/01F/BL1/005A.wav,core-upx/core/01F/BL1/005A.txt,core-upx/speaker_labels/lab/01F-BL1-005A.lab,1

In [6]:
# checking for null values
upx_metadata.isna().sum()

dataset_name           0
speaker_id             0
session_id             0
file_id                0
full_id                0
raw_wav_path           0
txt_path               0
speaker_label_path    17
class_label            0
dtype: int64

In [7]:
# checking for column names
print(upx_info_df.columns)
print(upx_metadata.columns)

Index(['SPEAKER-ID', 'GENDER', 'AGE-Y', 'AGE-M', 'AGE', 'SSD SUBTYPE'], dtype='str')
Index(['dataset_name', 'speaker_id', 'session_id', 'file_id', 'full_id',
       'raw_wav_path', 'txt_path', 'speaker_label_path', 'class_label'],
      dtype='str')

In [8]:
# renaming the speaker_id
upx_info_df=upx_info_df.rename(columns={"SPEAKER-ID":"speaker_id"})

In [9]:
print(upx_info_df.columns)
print(upx_metadata.columns)

Index(['speaker_id', 'GENDER', 'AGE-Y', 'AGE-M', 'AGE', 'SSD SUBTYPE'], dtype='str')
Index(['dataset_name', 'speaker_id', 'session_id', 'file_id', 'full_id',
       'raw_wav_path', 'txt_path', 'speaker_label_path', 'class_label'],
      dtype='str')

In [10]:
# merging the info data with the metadata
upx_metadata=upx_metadata.merge(
    upx_info_df,
    on = "speaker_id",
    how = "left")

In [11]:
upx_metadata.head()

,dataset_name,speaker_id,session_id,file_id,full_id,raw_wav_path,txt_path,speaker_label_path,class_label,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE
0,upx,01F,BL1,001E,01F-BL1-001E,core-upx/core/01F/BL1/001E.wav,core-upx/core/01F/BL1/001E.txt,core-upx/speaker_labels/lab/01F-BL1-001E.lab,1,Female,8,8,8.67,inconsistent phonological disorder
1,upx,01F,BL1,002E,01F-BL1-002E,core-upx/core/01F/BL1/002E.wav,core-upx/core/01F/BL1/002E.txt,core-upx/speaker_labels/lab/01F-BL1-002E.lab,1,Female,8,8,8.67,inconsistent phonological disorder
2,upx,01F,BL1,003A,01F-BL1-003A,core-upx/core/01F/BL1/003A.wav,core-upx/core/01F/BL1/003A.txt,core-upx/speaker_labels/lab/01F-BL1-003A.lab,1,Female,8,8,8.67,inconsistent phonological disorder
3,upx,01F,BL1,004A,01F-BL1-004A,core-upx/core/01F/BL1/004A.wav,core-upx/core/01F/BL1/004A.txt,core-upx/speaker_labels/lab/01F-BL1-004A.lab,1,Female,8,8,8.67,inconsistent phonological disorder
4,upx,01F,BL1,005A,01F-BL1-005A,core-upx/core/01F/BL1/005A.wav,core-upx/core/01F/BL1/005A.txt,core-upx/speaker_labels/lab/01F-BL1-005A.lab,1,Female,8,8,8.67,inconsistent phonological disorder

In [12]:
# rearranging the columns
upx_metadata = upx_metadata[
    [
        "dataset_name",
        "speaker_id",
        "session_id",
        "file_id",
        "GENDER",
        "AGE-Y",
        "AGE-M",
        "AGE",
        "SSD SUBTYPE",
        "full_id",
        "raw_wav_path",
        "txt_path",
        "speaker_label_path",
        "class_label"
    ]
]
upx_metadata.head()

,dataset_name,speaker_id,session_id,file_id,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE,full_id,raw_wav_path,txt_path,speaker_label_path,class_label
0,upx,01F,BL1,001E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-001E,core-upx/core/01F/BL1/001E.wav,core-upx/core/01F/BL1/001E.txt,core-upx/speaker_labels/lab/01F-BL1-001E.lab,1
1,upx,01F,BL1,002E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-002E,core-upx/core/01F/BL1/002E.wav,core-upx/core/01F/BL1/002E.txt,core-upx/speaker_labels/lab/01F-BL1-002E.lab,1
2,upx,01F,BL1,003A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-003A,core-upx/core/01F/BL1/003A.wav,core-upx/core/01F/BL1/003A.txt,core-upx/speaker_labels/lab/01F-BL1-003A.lab,1
3,upx,01F,BL1,004A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-004A,core-upx/core/01F/BL1/004A.wav,core-upx/core/01F/BL1/004A.txt,core-upx/speaker_labels/lab/01F-BL1-004A.lab,1
4,upx,01F,BL1,005A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-005A,core-upx/core/01F/BL1/005A.wav,core-upx/core/01F/BL1/005A.txt,core-upx/speaker_labels/lab/01F-BL1-005A.lab,1

In [13]:
# checking the missing values again for confirmation
upx_metadata.isna().sum()

dataset_name           0
speaker_id             0
session_id             0
file_id                0
GENDER                 0
AGE-Y                  0
AGE-M                  0
AGE                    0
SSD SUBTYPE            0
full_id                0
raw_wav_path           0
txt_path               0
speaker_label_path    17
class_label            0
dtype: int64

## Reading the prompt text for txt file

The prompt text will allow us to filter the recordings in pre-processing since some of the recordings are blank or contain irregular text information, which is not related with the actual children speeches.

In [14]:
# reading text from the text files
def read_prompt_text(txt_path):
    if pd.isna(txt_path):
        return None
    try:
        with open(txt_path, "r", encoding="utf-8") as f:
            return f.readline().strip()
    except Exception:
        return None

upx_metadata["prompt_text"] = upx_metadata["txt_path"].apply(read_prompt_text) # function will apply on each value on the column
upx_metadata.head()

,dataset_name,speaker_id,session_id,file_id,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE,full_id,raw_wav_path,txt_path,speaker_label_path,class_label,prompt_text
0,upx,01F,BL1,001E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-001E,core-upx/core/01F/BL1/001E.wav,core-upx/core/01F/BL1/001E.txt,core-upx/speaker_labels/lab/01F-BL1-001E.lab,1,Swallow
1,upx,01F,BL1,002E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-002E,core-upx/core/01F/BL1/002E.wav,core-upx/core/01F/BL1/002E.txt,core-upx/speaker_labels/lab/01F-BL1-002E.lab,1,Swallow
2,upx,01F,BL1,003A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-003A,core-upx/core/01F/BL1/003A.wav,core-upx/core/01F/BL1/003A.txt,core-upx/speaker_labels/lab/01F-BL1-003A.lab,1,elephant umbrella train swing
3,upx,01F,BL1,004A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-004A,core-upx/core/01F/BL1/004A.wav,core-upx/core/01F/BL1/004A.txt,core-upx/speaker_labels/lab/01F-BL1-004A.lab,1,bread duck giraffe five
4,upx,01F,BL1,005A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-005A,core-upx/core/01F/BL1/005A.wav,core-upx/core/01F/BL1/005A.txt,core-upx/speaker_labels/lab/01F-BL1-005A.lab,1,teeth watch orange school

## Audio Segmentation using speaker_label_path

Audio Segmentation is performed using available speaker labels timestamps for child speech part inside the original raw recordings.

In [15]:
# helper function to perform the segmentation
def diarize_with_speaker_labels(wav_path, lab_path, output_path,
                                keep_label="CHILD",
                                margin_ms=20, # margin to remove the cross boundry issue between child and therapist speech
                                min_seg_ms=100): # to filter the recordings having duration less than 100 milli seconds
   
    audio, sr = sf.read(wav_path)

    # converting stereo to mono channel
    if audio.ndim > 1:
        audio = np.mean(audio, axis=1)

    margin_samples = round(sr * margin_ms / 1000)
    min_seg_samples = round(sr * min_seg_ms / 1000)
    target_label = keep_label.upper()

    kept_segments = []
    found_child = False
    found_slt = False
    has_target_label = False
    n_target_segments_raw = 0

    with open(lab_path, "r", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) != 3:
                continue

            start_htk = int(parts[0])
            end_htk = int(parts[1])
            label = parts[2].strip().upper()

            if label == "CHILD":
                found_child = True
            if label == "SLT":
                found_slt = True

            if label == target_label:
                has_target_label = True
                n_target_segments_raw += 1

                start_sample = round(start_htk * sr / 10_000_000)
                end_sample = round(end_htk * sr / 10_000_000)

                # trim boundaries slightly
                start_sample += margin_samples
                end_sample -= margin_samples

                # clip bounds
                start_sample = max(0, start_sample)
                end_sample = min(len(audio), end_sample)

                if end_sample > start_sample:
                    seg = audio[start_sample:end_sample]
                    if len(seg) >= min_seg_samples:
                        kept_segments.append(seg)

    raw_duration_sec = len(audio) / sr

    if not kept_segments:
        return {
            "status": "no_target_labels" if not has_target_label else "no_target_segments_after_filters",
            "target_label": target_label,
            "sample_rate": sr,
            "raw_duration_sec": raw_duration_sec,
            "child_duration_sec": 0.0,
            "n_child_segments": 0,
            "has_target_label": has_target_label,
            "n_target_segments_raw": n_target_segments_raw,
            "n_target_segments_kept": 0,
            "has_child": found_child,
            "has_slt": found_slt
        }

    child_audio = np.concatenate(kept_segments)
    sf.write(output_path, child_audio, sr)

    return {
        "status": "processed",
        "target_label": target_label,
        "sample_rate": sr,
        "raw_duration_sec": raw_duration_sec,
        "child_duration_sec": len(child_audio) / sr,
        "n_child_segments": len(kept_segments),
        "has_target_label": has_target_label,
        "n_target_segments_raw": n_target_segments_raw,
        "n_target_segments_kept": len(kept_segments),
        "has_child": found_child,
        "has_slt": found_slt
    }

In [16]:
# storing the processed recordings after segmentation
row = upx_metadata.iloc[0]

output_dir = Path("upx_processed_child_wav")
output_dir.mkdir(exist_ok=True)

output_path = output_dir / f"{row['full_id']}_child.wav"

result = diarize_with_speaker_labels(
    wav_path=row["raw_wav_path"],
    lab_path=row["speaker_label_path"],
    output_path=output_path
)

print(result)
print("Saved to:", output_path)

{'status': 'processed', 'target_label': 'CHILD', 'sample_rate': 22050, 'raw_duration_sec': 7.848344671201814, 'child_duration_sec': 1.32, 'n_child_segments': 1, 'has_target_label': True, 'n_target_segments_raw': 1, 'n_target_segments_kept': 1, 'has_child': True, 'has_slt': True}
Saved to: upx_processed_child_wav/01F-BL1-001E_child.wav

In [17]:
upx_metadata.loc[0, "processed_child_wav_path"] = str(output_path)
upx_metadata.loc[0, "raw_duration_sec"] = result["raw_duration_sec"]
upx_metadata.loc[0, "child_duration_sec"] = result["child_duration_sec"]
upx_metadata.loc[0, "n_child_segments"] = result["n_child_segments"]
upx_metadata.loc[0, "has_child"] = result["has_child"]
upx_metadata.loc[0, "has_slt"] = result["has_slt"]
upx_metadata.loc[0, "status"] = result["status"]
upx_metadata.loc[0, "diarization_method"] = "provided_speaker_labels"

In [18]:
# testing before and after recording for first row
print("Before:")
display(Audio(row["raw_wav_path"]))

print("After:")
Audio(row["raw_wav_path"])
Audio(str(output_path))

Before:

After:

In [19]:
upx_metadata.head()

,dataset_name,speaker_id,session_id,file_id,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE,full_id,...,class_label,prompt_text,processed_child_wav_path,raw_duration_sec,child_duration_sec,n_child_segments,has_child,has_slt,status,diarization_method
0,upx,01F,BL1,001E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-001E,...,1,Swallow,upx_processed_child_wav/01F-BL1-001E_child.wav,7.848345,1.32,1.0,True,True,processed,provided_speaker_labels
1,upx,01F,BL1,002E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-002E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,upx,01F,BL1,003A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-003A,...,1,elephant umbrella train swing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,upx,01F,BL1,004A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-004A,...,1,bread duck giraffe five,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,upx,01F,BL1,005A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-005A,...,1,teeth watch orange school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Now applying segmentation on whole data frame

In [20]:
output_dir = Path("upx_processed_child_wav")
output_dir.mkdir(exist_ok=True)

for idx, row in upx_metadata.iterrows():
    wav_path = row["raw_wav_path"]
    lab_path = row["speaker_label_path"]

    if pd.isna(wav_path) or pd.isna(lab_path):
        upx_metadata.loc[idx, "status"] = "missing_path"
        continue

    output_path = output_dir / f"{row['full_id']}_child.wav"

    try:
        result = diarize_with_speaker_labels(
            wav_path=wav_path,
            lab_path=lab_path,
            output_path=output_path
        )

        upx_metadata.loc[idx, "processed_child_wav_path"] = str(output_path)
        upx_metadata.loc[idx, "raw_duration_sec"] = result["raw_duration_sec"]
        upx_metadata.loc[idx, "child_duration_sec"] = result["child_duration_sec"]
        upx_metadata.loc[idx, "n_child_segments"] = result["n_child_segments"]
        upx_metadata.loc[idx, "has_child"] = result["has_child"]
        upx_metadata.loc[idx, "has_slt"] = result["has_slt"]
        upx_metadata.loc[idx, "status"] = result["status"]
        upx_metadata.loc[idx, "diarization_method"] = "provided_speaker_labels"

    except Exception as e:
        upx_metadata.loc[idx, "status"] = f"error: {e}"

In [21]:
# checking the data again
upx_metadata.head()

,dataset_name,speaker_id,session_id,file_id,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE,full_id,...,class_label,prompt_text,processed_child_wav_path,raw_duration_sec,child_duration_sec,n_child_segments,has_child,has_slt,status,diarization_method
0,upx,01F,BL1,001E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-001E,...,1,Swallow,upx_processed_child_wav/01F-BL1-001E_child.wav,7.848345,1.320000,1.0,True,True,processed,provided_speaker_labels
1,upx,01F,BL1,002E,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-002E,...,1,Swallow,upx_processed_child_wav/01F-BL1-002E_child.wav,12.074376,2.480045,3.0,True,True,processed,provided_speaker_labels
2,upx,01F,BL1,003A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-003A,...,1,elephant umbrella train swing,upx_processed_child_wav/01F-BL1-003A_child.wav,9.659501,4.090023,4.0,True,False,processed,provided_speaker_labels
3,upx,01F,BL1,004A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-004A,...,1,bread duck giraffe five,upx_processed_child_wav/01F-BL1-004A_child.wav,11.470658,4.560000,6.0,True,False,processed,provided_speaker_labels
4,upx,01F,BL1,005A,Female,8,8,8.67,inconsistent phonological disorder,01F-BL1-005A,...,1,teeth watch orange school,upx_processed_child_wav/01F-BL1-005A_child.wav,11.470658,5.430023,4.0,True,False,processed,provided_speaker_labels

In [22]:
row1=upx_metadata.iloc[1]
Audio(filename=row1["raw_wav_path"])

In [23]:
row1=upx_metadata.iloc[1]
Audio(filename=row1["processed_child_wav_path"])

In [24]:
# testing row index 15 before segmentation
row=upx_metadata.iloc[15]
Audio(filename=row["raw_wav_path"])

In [25]:
# testing row index 15 before segmentation
row=upx_metadata.iloc[15]
Audio(filename=row["processed_child_wav_path"])

In [26]:
# checking the null values again
upx_metadata.isna().sum()

dataset_name                 0
speaker_id                   0
session_id                   0
file_id                      0
GENDER                       0
AGE-Y                        0
AGE-M                        0
AGE                          0
SSD SUBTYPE                  0
full_id                      0
raw_wav_path                 0
txt_path                     0
speaker_label_path          17
class_label                  0
prompt_text                  0
processed_child_wav_path    17
raw_duration_sec            17
child_duration_sec          17
n_child_segments            17
has_child                   17
has_slt                     17
status                       0
diarization_method          17
dtype: int64

In [27]:
upx_metadata[upx_metadata["speaker_label_path"].isna()]

,dataset_name,speaker_id,session_id,file_id,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE,full_id,...,class_label,prompt_text,processed_child_wav_path,raw_duration_sec,child_duration_sec,n_child_segments,has_child,has_slt,status,diarization_method
959,upx,07M,BL2,055D,Male,8,11,8.92,childhood apraxia of speech,07M-BL2-055D,...,1,ptk-1SD,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
962,upx,07M,BL2,058D,Male,8,11,8.92,childhood apraxia of speech,07M-BL2-058D,...,1,ptk+2SD,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1014,upx,07M,BL4,001E,Male,8,11,8.92,childhood apraxia of speech,07M-BL4-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1106,upx,08M,BL1,044E,Male,10,2,10.17,childhood apraxia of speech,08M-BL1-044E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1346,upx,10M,BL2,001E,Male,13,4,13.33,childhood apraxia of speech,10M-BL2-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1399,upx,10M,BL2,054E,Male,13,4,13.33,childhood apraxia of speech,10M-BL2-054E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1444,upx,10M,BL3,045E,Male,13,4,13.33,childhood apraxia of speech,10M-BL3-045E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1481,upx,10M,BL4,037E,Male,13,4,13.33,childhood apraxia of speech,10M-BL4-037E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1553,upx,12M,BL1,001E,Male,6,3,6.25,phonological delay,12M-BL1-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1664,upx,12M,BL3,001E,Male,6,3,6.25,phonological delay,12M-BL3-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1913,upx,14M,BL2,002E,Male,6,10,6.83,vowel disorder,14M-BL2-002E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1958,upx,14M,BL2,047E,Male,6,10,6.83,vowel disorder,14M-BL2-047E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
1984,upx,15M,BL1,001E,Male,6,1,6.08,phonological delay,15M-BL1-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
2218,upx,16M,BL3,001E,Male,7,7,7.58,articulation disorder,16M-BL3-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
2298,upx,17M,BL2,001E,Male,13,2,13.17,phonological delay,17M-BL2-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
2579,upx,19M,BL3,001E,Male,10,0,10.00,phonological delay,19M-BL3-001E,...,1,Swallow,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN
2696,upx,20M,BL2,009A,Male,9,2,9.17,articulation disorder,20M-BL2-009A,...,1,scrape stop slow closet,NaN,NaN,NaN,NaN,NaN,NaN,missing_path,NaN

### About 17 rows have missing child labels, which means that their segmentation is not possible based on our approach. So we are dropping these instances.

In [28]:
# dropping missing child labels instances
upx_metadata.dropna(axis=0, inplace=True)

In [29]:
# checking for empty rows again.
upx_metadata.isna().sum()

dataset_name                0
speaker_id                  0
session_id                  0
file_id                     0
GENDER                      0
AGE-Y                       0
AGE-M                       0
AGE                         0
SSD SUBTYPE                 0
full_id                     0
raw_wav_path                0
txt_path                    0
speaker_label_path          0
class_label                 0
prompt_text                 0
processed_child_wav_path    0
raw_duration_sec            0
child_duration_sec          0
n_child_segments            0
has_child                   0
has_slt                     0
status                      0
diarization_method          0
dtype: int64

In [30]:
# checking all values inside the column "has_child"
upx_metadata["has_child"].unique()

array([True, False], dtype=object)

In [31]:
# checking for false values rows
upx_metadata[upx_metadata["has_child"] == False]

,dataset_name,speaker_id,session_id,file_id,GENDER,AGE-Y,AGE-M,AGE,SSD SUBTYPE,full_id,...,class_label,prompt_text,processed_child_wav_path,raw_duration_sec,child_duration_sec,n_child_segments,has_child,has_slt,status,diarization_method
326,upx,03F,BL2,001E,Female,10,11,10.92,childhood apraxia of speech,03F-BL2-001E,...,1,Swallow,upx_processed_child_wav/03F-BL2-001E_child.wav,7.848345,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
376,upx,03F,BL3,001E,Female,10,11,10.92,childhood apraxia of speech,03F-BL3-001E,...,1,Swallow,upx_processed_child_wav/03F-BL3-001E_child.wav,10.263220,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
473,upx,04M,BL1,001E,Male,7,2,7.17,phonological delay,04M-BL1-001E,...,1,Swallow,upx_processed_child_wav/04M-BL1-001E_child.wav,5.433469,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
1013,upx,07M,BL3,051E,Male,8,11,8.92,childhood apraxia of speech,07M-BL3-051E,...,1,Swallow,upx_processed_child_wav/07M-BL3-051E_child.wav,10.263220,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
1062,upx,07M,BL5,024E,Male,8,11,8.92,childhood apraxia of speech,07M-BL5-024E,...,1,Swallow,upx_processed_child_wav/07M-BL5-024E_child.wav,3.622313,0.0,0.0,False,False,no_target_labels,provided_speaker_labels
1196,upx,08M,BL3,060E,Male,10,2,10.17,childhood apraxia of speech,08M-BL3-060E,...,1,Swallow,upx_processed_child_wav/08M-BL3-060E_child.wav,4.226032,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
1230,upx,09M,BL2,001E,Male,7,9,7.75,phonological disorder,09M-BL2-001E,...,1,Swallow,upx_processed_child_wav/09M-BL2-001E_child.wav,8.452063,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
1345,upx,10M,BL1,048E,Male,13,4,13.33,childhood apraxia of speech,10M-BL1-048E,...,1,Swallow,upx_processed_child_wav/10M-BL1-048E_child.wav,7.848345,0.0,0.0,False,False,no_target_labels,provided_speaker_labels
1445,upx,10M,BL4,001E,Male,13,4,13.33,childhood apraxia of speech,10M-BL4-001E,...,1,Swallow,upx_processed_child_wav/10M-BL4-001E_child.wav,6.037188,0.0,0.0,False,False,no_target_labels,provided_speaker_labels
1855,upx,13M,BL3,036E,Male,7,4,7.33,inconsistent phonological disorder,13M-BL3-036E,...,1,Swallow,upx_processed_child_wav/13M-BL3-036E_child.wav,7.848345,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
2038,upx,15M,BL1,055E,Male,6,1,6.08,phonological delay,15M-BL1-055E,...,1,Swallow,upx_processed_child_wav/15M-BL1-055E_child.wav,7.244626,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
2400,upx,18F,BL1,039E,Female,7,1,7.08,articulation disorder,18F-BL1-039E,...,1,Swallow,upx_processed_child_wav/18F-BL1-039E_child.wav,5.433469,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
2578,upx,19M,BL2,032E,Male,10,0,10.00,phonological delay,19M-BL2-032E,...,1,Swallow,upx_processed_child_wav/19M-BL2-032E_child.wav,4.829751,0.0,0.0,False,True,no_target_labels,provided_speaker_labels
2603,upx,19M,BL4,001E,Male,10,0,10.00,phonological delay,19M-BL4-001E,...,1,Swallow,upx_processed_child_wav/19M-BL4-001E_child.wav,4.829751,0.0,0.0,False,True,no_target_labels,provided_speaker_labels

### So there are about 17 more records which does not have child labels. So we need to remove them as well.

In [32]:
upx_metadata.drop(upx_metadata[upx_metadata["has_child"] == False].index, inplace=True)

In [33]:
# checking the values again
upx_metadata["has_child"].unique()

array([True], dtype=object)

In [34]:
upx_metadata["prompt_text"].unique()

<ArrowStringArray>
[                           'Swallow',      'elephant umbrella train swing',
            'bread duck giraffe five',          'teeth watch orange school',
 'crab biscuits thank-you helicopter',              'egg splash square pig',
            'gloves queen three frog',       'yellow strawberry spider web',
           'sheep snake pram feather',     'tomato monkey toothbrush apple',
 ...
           'zombie nose zone whistle',                 'bays puss size sip',
             'seep glasses xylophone',               'sucks sore zoo shoot',
            'hoist suit sheep shower',               'smoke speed ship fez',
                              's s s',                         'ees os ahs',
                           'sh sh sh',                        'she sho sha']
Length: 450, dtype: str

In [35]:
upx_metadata.shape

(2758, 23)

In [36]:
# checking for prompt text
vc = upx_metadata["prompt_text"].value_counts(dropna=False)
print(vc.to_string())

prompt_text
Swallow                                                            91
down link pat get                                                  28
Kenny drank a tiny tin of coke                                     28
Ken likes scones with cream and apricot jam                        27
My Granny Maggie got a golden gown                                 26
Baby Gary's got a bag of lego                                      26
scrawny tube toot cream                                            25
smokey meet lit broccoli                                           25
team gap grovel tip                                                25
deer buggy debt crow                                               25
avocado KitKat digger dumb                                         25
dawn fig garden tab                                                25
Coca-Cola pack bog bed                                             25
tool hockey Maggie gone                                            25
gift tie pot rogue                                                 25
make boat cape mag                                                 25
gown meek gum ten                                                  25
cool coy gore kitten                                               25
making tactic kip toy                                              25
road gate scream goose                                             25
monkey tiger gear core                                             25
kicking ken peck yucky                                             25
tape cop pet slug                                                  25
green mate boak beg                                                25
Kevin got a cab to the coast                                       25
Happy Karen is making a cake                                       25
packing Hague top guy                                              24
cube Mike couch mock                                               24
took think muck cub                                                24
door keep date scone                                               24
die kai mut cab                                                    24
tore tub cookie pecking                                            23
crab biscuits thank-you helicopter                                 19
animals caravan caterpillar butterfly                              18
ch j l l r w y h zh                                                18
knife van ear this                                                 17
ambulance hippopotamus computer                                    17
spaghetti vegetables helicopter                                    17
gloves queen three frog                                            16
sheep snake pram feather                                           16
scissors fishing lighthouse zebra                                  16
rye why yeah high mezh                                             16
elephant umbrella train swing                                      15
bread duck giraffe five                                            15
teeth watch orange school                                          15
egg splash square pig                                              15
yellow strawberry spider web                                       15
tomato monkey toothbrush apple                                     15
book boy                                                           15
f v th th s z sh                                                   15
mad lick might ski                                                 15
peeking                                                            15
kitchen sausage tiger rabbit                                       14
jam legs ring watch                                                14
chew jai lie eel                                                   14
thy sigh zoo shy                                                   13
pig bird teeth door                                                12
car girl moon knife                                                12
fish van thumb this                                                12
sock zebra sheep chair                                             12
yellow house five foot                                             12
crab boy orange snake                                              12
television ear                                                     12
Shelby found seashells on the shore                                11
Shrek was shampooing his hair in the shower                        11
Sean is washing a dirty dish                                       11
The musicians got an invitation to a celebration                   11
I saw Sam sitting on a bus                                         11
mad lick might ski peeking                                         10
celebration swish shine invitation                                 10
shoot leash shock push                                             10
sign cashew lotion seep                                            10
police station sucks dishwasher                                    10
bays sore washing sour                                             10
shack puss mesh shower                                             10
shrink composer ship shave                                         10
mushroom imagination Shrek musician                                10
mosh shell sip mess                                                10
sheep beige shucks blush                                           10
suit moss collage shore                                            10
sack seashell sell lease                                           10
save shriek bruise lash                                            10
eraser mass Swiss sock                                             10
radishes sharpener mushy shrew                                     10
shampooing pushing                                                 10
Sean the sheep was on the ship                                     10
The eye doctor measures your vision                                10
The hamster scrambled up Stuart s sleeve                           10
ing fie vie thigh                                                   9
rag frog bridge Shrek hear                                          9
red cry tar prince                                                  9
grass war tear tractor                                              9
reel dragon rock rake                                               9
row room ripe cure sore                                             9
Ron raked the grass around the rock                                 9
The red tractor went over the bridge                                9
The dragon was friends with the frog prince                         9
Liz bruise shock shy                                                9
p b t d k g m n ng                                                  8
jazz swish postman mess                                             8
iceberg-lettuce Caesar Susan                                        8
scrape stop slow closet                                             8
sigh sausages snail beige                                           8
composure snow Pisces use                                           8
sack bus sock zero                                                  8
sell Lucy sledge shucks                                             8
start shave hazard policeman                                        8
mosh zen mash eraser                                                8
leash soil sour Zane                                                8
shell mesh smell mass                                               8
shack xylophone save shore                                          8
high-school zap bicycles                                            8
nice spot scary muscle                                              8
moss Swiss buzz peas                                                8
Liz played with the toys and was amused with the puzzle             8
Zoe played jazz music on the xylophone                              8
Sam the policeman stopped the silly girls chasing the pussy cat     8
The zebra was at the zoo                                            8
p-3SD                                                               7
p-2SD                                                               7
p-1SD                                                               7
p-mean                                                              7
p+1SD                                                               7
p+2SD                                                               7
t-3SD                                                               7
t-2SD                                                               7
t-1SD                                                               7
t-mean                                                              7
t+1SD                                                               7
t+2SD                                                               7
k-3SD                                                               7
k-2SD                                                               7
k-1SD                                                               7
k-mean                                                              7
k+2SD                                                               7
tk-3SD                                                              7
tk-2SD                                                              7
tk-1SD                                                              7
tk-mean                                                             7
tk+1SD                                                              7
tk+2SD                                                              7
ptk-3SD                                                             7
ptk-2SD                                                             7
ptk-mean                                                            7
ptk+1SD                                                             7
Connected speech 1                                                  7
Connected speech 2                                                  7
Connected speech 3                                                  7
key guy my nigh                                                     6
k+1SD                                                               6
ptk-1SD                                                             6
ptk+2SD                                                             6
Naughty Neil saw a robin in a nest                                  6
Tiny Tim is putting a hat on                                        6
My Daddy mended a door                                              6
Connected speech picture 1                                          5
Connected speech picture 2                                          5
Connected speech picture 3                                          5
The were six children were on the school bus                        5
high lease zip puzzle                                               5
toys helium composer hum                                            5
home face scrambled-eggs                                            5
amusing desert hip blizzard                                         5
sip whistle hack sizing                                             5
zombie nose zone hoot                                               5
how bays puss size                                                  5
seep glasses helicopter xylophone                                   5
sucks hock sore zoo                                                 5
hoist hell suit sheep                                               5
smoke speed ship heap                                               5
fossil push messy chasing                                           5
gin pitch birthday perch                                            4
Batman was hanging from the roof                                    4
It's a tea Pam                                                      3
It's a key Pam                                                      3
shrew shrink scone grovel                                           3
frog cry grumpy dream                                               3
speed tram tractor scrawny                                          3
brother crow smell slow                                             3
snail bottle scream mushroom                                        3
ski prince green Shrek                                              3
cream stop shriek dragon                                            3
strain star scary Shrek                                             3
Stacey ate a scone with apricot jam and cream                       3
The scary crow had a dream about a dragon                           3
The slow snail was friends with the grumpy frog                     3
Shrek is a green ogre                                               3
A tram and a tractor are types of transport                         3
The potion in the bottle made the girl shrink                       3
ee ay eh ah aw                                                      3
oh oo uh ih                                                         3
biscuits ran rang ten                                               3
earth packing cart pan                                              3
tip circle set girls                                                3
picking pearl tap batman                                            3
sat pin Jenny tipping                                               3
sit banging kilt tan                                                3
ringing ted teddy tad                                               3
lit bit barn Jan                                                    3
wren pick kit pencil                                                3
ban barley sitting cat                                              3
pecking farming bat nervous                                         3
patch ring Jen let                                                  3
tin peck pen bin                                                    3
parch perching Ben pack                                             3
bet betting whirl                                                   3
Ben sat on the pin                                                  3
The teddy was called Jenny                                          3
Lizzy was eating the biscuits                                       3
Jen and Jan were drinking gin                                       3
mask chasing less mad                                               3
core heat come hoe                                                  3
coot who eye tie                                                    3
hi cape seat op                                                     3
kit co seep hum                                                     3
tea ticking eat tub                                                 3
Tam Sam cub hip                                                     3
tore say cop hit                                                    3
oh hell hen eating                                                  3
oar kai sop heap                                                    3
kip telly kay seeping                                               3
toot sell sit cake                                                  3
Kelly keeping am hub                                                3
seating tip so top                                                  3
suit tick keep Elle                                                 3
sum tell he key                                                     3
sip kicking heating sick                                            3
hay sigh Ellie sub                                                  3
um ache take tape                                                   3
ham toe ten it                                                      3
sake kick calm sore ape                                             3
ken hop tum hake see                                                3
He found a key in a cup of tea                                      3
Elle wanted to sell ten hens to Ken                                 3
The cape and tape were in the hay                                   3
Kelly's hip had an ache from falling in a tip                       3
Sue's toe was sore from banging it on an oar                        3
Sam, Tam and kai sore a suit and tie                                3
Ellie was eating ham and hake                                       3
thing tool thin gown                                                3
win debt date top                                                   3
donkey bottle pint kai                                              3
pack bone dim cub                                                   3
tore bog dream coy                                                  3
cool strain patting dawn                                            3
gore meek tab boak                                                  3
meaning guy road nab                                                3
gum tactic bud cab                                                  3
toy cop ten owning                                                  3
bug dumb big bid                                                    3
neap tie ken fading                                                 3
leak gone boat made                                                 3
wing gnome pat KitKat                                               3
tram die potty think                                                3
deer mean dab gear                                                  3
gate pine bed manning                                               3
tip mag lead rogue                                                  3
kitten get meet pan                                                 3
money cape pod Paddy                                                3
leading tub team garden                                             3
Eddie gap monkey mad                                                3
kip meeting down donuts                                             3
packing mood core buddy                                             3
star beg door tape keep                                             3
Paddy and Eddie met at the tool store                               3
Monkeys have ten tiny toes                                          3
fishes fossil push messy                                            3
shoot shower hay fez chasing                                        3
pie buy tie die                                                     3
ate buddy down                                                      3
patting Paddy too                                                   3
dream tall Eddie                                                    3
puss tie dim                                                        3
ace houses bud                                                      3
mass die tram                                                       3
pod tactic saucy                                                    3
dote recipe dumb                                                    3
tad dawn mat                                                        3
road desk pacifier                                                  3
but led moss                                                        3
fading louse said                                                   3
donuts sad strain                                                   3
sum Tay Sue                                                         3
deer feasting door                                                  3
sip team dab                                                        3

#### So some prompt text is not relevant, which shows that we need to remove these instances as well.

In [37]:
col = "prompt_text"

#  Regex for rows to remove
score_code_pat = r"^(?:ptk|tk|p|t|k)(?:[+-]\d+SD|-mean)$"
task_label_pat = r"^Connected speech(?: picture)?\s*\d+$"

remove_pat = re.compile(
    f"(?:{score_code_pat})|(?:{task_label_pat})",
    flags=re.IGNORECASE
)

# building mask
s = upx_metadata[col].fillna("").astype(str).str.strip()
mask_remove = s.str.match(remove_pat, na=False)

# now getting clean dataframe
upx_metadata_clean = upx_metadata.loc[~mask_remove].copy()

print("Before:", len(upx_metadata))
print("Removed:", mask_remove.sum())
print("After:", len(upx_metadata_clean))

Before: 2758
Removed: 243
After: 2515

In [38]:
# storing the clean upx_metadata csv file
upx_metadata_clean.to_csv("upx_metadata_clean.csv", index=False)